apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lcls-fel-surrogate-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/slaclab/lcls-fel-surrogate-deployment
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: lume-online-ml
  syncPolicy:
    automated: {}