apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lcls-fel-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/slaclab/lume-fel-deployment
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: lume-online-ml
  syncPolicy:
    automated: {}